// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/repository/interfaces/auth.go

// Package mockrepo is a generated GoMock package.
package mockrepo

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/nikhilnarayanan623/ecommerce-gin-clean-arch/pkg/domain"
)

// MockAuthRepository is a mock of AuthRepository interface.
type MockAuthRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthRepositoryMockRecorder
}

// MockAuthRepositoryMockRecorder is the mock recorder for MockAuthRepository.
type MockAuthRepositoryMockRecorder struct {
	mock *MockAuthRepository
}

// NewMockAuthRepository creates a new mock instance.
func NewMockAuthRepository(ctrl *gomock.Controller) *MockAuthRepository {
	mock := &MockAuthRepository{ctrl: ctrl}
	mock.recorder = &MockAuthRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthRepository) EXPECT() *MockAuthRepositoryMockRecorder {
	return m.recorder
}

// FindOtpSession mocks base method.
func (m *MockAuthRepository) FindOtpSession(ctx context.Context, otpID string) (domain.OtpSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOtpSession", ctx, otpID)
	ret0, _ := ret[0].(domain.OtpSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOtpSession indicates an expected call of FindOtpSession.
func (mr *MockAuthRepositoryMockRecorder) FindOtpSession(ctx, otpID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOtpSession", reflect.TypeOf((*MockAuthRepository)(nil).FindOtpSession), ctx, otpID)
}

// FindRefreshSessionByTokenID mocks base method.
func (m *MockAuthRepository) FindRefreshSessionByTokenID(ctx context.Context, tokenID string) (domain.RefreshSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRefreshSessionByTokenID", ctx, tokenID)
	ret0, _ := ret[0].(domain.RefreshSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRefreshSessionByTokenID indicates an expected call of FindRefreshSessionByTokenID.
func (mr *MockAuthRepositoryMockRecorder) FindRefreshSessionByTokenID(ctx, tokenID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRefreshSessionByTokenID", reflect.TypeOf((*MockAuthRepository)(nil).FindRefreshSessionByTokenID), ctx, tokenID)
}

// SaveOtpSession mocks base method.
func (m *MockAuthRepository) SaveOtpSession(ctx context.Context, otpSession domain.OtpSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveOtpSession", ctx, otpSession)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveOtpSession indicates an expected call of SaveOtpSession.
func (mr *MockAuthRepositoryMockRecorder) SaveOtpSession(ctx, otpSession interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveOtpSession", reflect.TypeOf((*MockAuthRepository)(nil).SaveOtpSession), ctx, otpSession)
}

// SaveRefreshSession mocks base method.
func (m *MockAuthRepository) SaveRefreshSession(ctx context.Context, refreshSession domain.RefreshSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRefreshSession", ctx, refreshSession)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveRefreshSession indicates an expected call of SaveRefreshSession.
func (mr *MockAuthRepositoryMockRecorder) SaveRefreshSession(ctx, refreshSession interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRefreshSession", reflect.TypeOf((*MockAuthRepository)(nil).SaveRefreshSession), ctx, refreshSession)
}
